training_blog:
    resource: "@TrainingBundle/Resources/config/routing.yml"
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path:   /login
    defaults: {_controller: TrainingBundle:User:login}

login_check:
    path:   /login_check
    defaults: {_controller: TrainingBundle:User:login_check}

logout:
    path:   /logout
    
imag_ldap:
  resource: "@IMAGLdapBundle/Resources/config/routing.yml"
