acme_blog:
    path:     /
    defaults: { _controller: AcmeBlogBundle:BlogPost:index }

acme_blog_post:
    resource: "@AcmeBlogBundle/Controller/BlogPostController.php"
    type:     annotation
    prefix:   /post

acme_user:
    resource: "@AcmeBlogBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /user
